<script>
    import { onMount } from "svelte";

    onMount(() => {
        (adsbygoogle = window.adsbygoogle || []).push({});
    });
</script>

<style>
    div.g_ads-bar {
        max-width: 100%;
    }
</style>

<div class="g_ads-bar">
    <ins
        class="adsbygoogle"
        style="display:block"
        data-ad-format="fluid"
        data-ad-layout-key="-ef+6k-30-ac+ty"
        data-ad-client="ca-pub-7630389826147489"
        data-ad-slot="2294645793"
    ></ins>
</div>